"use client";

import { useQuery } from "@tanstack/react-query";
import { useCrunchContext } from "@/modules/crunch/application/context/crunchContext";
import { getNodeCheckpoints } from "../../infrastructure/nodeService";

/**
 * Fetch pending checkpoints from the coordinator node.
 * These are checkpoints generated by the node that haven't been submitted on-chain yet.
 */
export function useGetPendingNodeCheckpoints() {
  const { crunchName } = useCrunchContext();

  const query = useQuery({
    queryKey: ["node-checkpoints", crunchName, "PENDING"],
    queryFn: () => getNodeCheckpoints(crunchName, "PENDING"),
    enabled: !!crunchName,
    retry: false,
    refetchInterval: 30_000,
  });

  return {
    pendingCheckpoints: query.data ?? [],
    pendingCheckpointsLoading: query.isLoading,
    pendingCheckpointsError: query.error,
  };
}
