import { LeaderboardColumn } from "./types";

export const columns: LeaderboardColumn[] = [
  {
    id: 0,
    type: "PROJECT",
    property: "model_id",
    format: null,
    display_name: null,
    tooltip: null,
    native_configuration: null,
    order: 0,
  },
  {
    id: 1,
    type: "STATUS",
    property: "status",
    format: null,
    display_name: null,
    tooltip: null,
    native_configuration: null,
    order: 0,
  },
  {
    id: 2,
    type: "VALUE",
    property: "score_recent",
    format: "decimal-1",
    display_name: "Recent Score",
    tooltip: "The score of the player over the last 24 hours.",
    native_configuration: null,
    order: 20,
  },
  {
    id: 3,
    type: "VALUE",
    property: "score_steady",
    format: "decimal-2",
    display_name: "Steady Score",
    tooltip: "The score of the player over the last 72 hours.",
    native_configuration: null,
    order: 30,
  },
  {
    id: 4,
    type: "VALUE",
    property: "score_anchor",
    format: "decimal-3",
    display_name: "Recent Score",
    tooltip: "The score of the player over the last 7 days.",
    native_configuration: null,
    order: 40,
  },
];
